import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';
import { uploadToCloudinary } from '../../utils/cloudinary';

export interface LookbookPage {
  imageUrl: string;
  title?: string;
  subtitle?: string;
}

export interface LookbookMeta {
  collectionName?: string;
  brandName?: string;
}

export async function generateLookbookPdf({
  pages,
  meta,
}: {
  pages: LookbookPage[];
  meta?: LookbookMeta;
}) {
  if (!pages || pages.length === 0) {
    throw new Error('No pages provided for PDF generation.');
  }

  // Temp directory
  const tempDir = path.join(process.cwd(), 'tmp');
  if (!fs.existsSync(tempDir)) {
    fs.mkdirSync(tempDir, { recursive: true });
  }

  const filename = `lookbook_${Date.now()}.pdf`;
  const filePath = path.join(tempDir, filename);

  const doc = new PDFDocument({
    size: 'A4',
    margin: 40,
  });

  const writeStream = fs.createWriteStream(filePath);

  const pdfReady = new Promise<void>((resolve, reject) => {
    writeStream.on('finish', () => resolve());
    writeStream.on('error', (err) => reject(err));
  });

  doc.pipe(writeStream);

  // ===== COVER PAGE =====
  if (meta?.collectionName || meta?.brandName) {
    doc.fontSize(26).text(meta.collectionName ?? 'Lookbook', { align: 'center' });

    if (meta?.brandName) {
      doc.moveDown();
      doc.fontSize(18).text(meta.brandName, { align: 'center' });
    }

    doc.moveDown(2);
    doc.fontSize(12).text('Generated by MagicReel', { align: 'center' });

    doc.addPage();
  }

  // ===== CONTENT PAGES =====
  for (let index = 0; index < pages.length; index++) {
    const page = pages[index];

    if (index > 0 || meta?.collectionName || meta?.brandName) {
      doc.addPage();
    }

    // Title
    if (page.title) {
      doc.fontSize(18).text(page.title, { align: 'left' });
      doc.moveDown(0.5);
    }

    // Subtitle
    if (page.subtitle) {
      doc.fontSize(12).text(page.subtitle, { align: 'left' });
      doc.moveDown(1);
    }

    // Image
    try {
      const buffer = await fetchImageBuffer(page.imageUrl);

      const maxWidth =
        doc.page.width - doc.page.margins.left - doc.page.margins.right;

      const maxHeight = doc.page.height - doc.y - 60; // leave bottom margin

      doc.image(buffer, {
        fit: [maxWidth, maxHeight],
        align: 'center',
        valign: 'center',
      });
    } catch (err: any) {
      console.error('PDF IMAGE ERROR →', err?.message);
      doc
        .fillColor('red')
        .fontSize(10)
        .text(`⚠ Failed to load image: ${page.imageUrl}`)
        .fillColor('black');
    }
  }

  // Finalize PDF
  doc.end();
  await pdfReady;

  // ===== UPLOAD TO CLOUDINARY =====
  const uploadRes = await uploadToCloudinary(filePath, {
    folder: 'magicreel/lookbooks',
    resource_type: 'raw',
    public_id: path.parse(filename).name,
  });

  // Cleanup
  try {
    fs.unlinkSync(filePath);
  } catch (cleanupErr) {
    console.error('PDF TEMP FILE CLEANUP ERROR →', cleanupErr);
  }

  return {
    pdfUrl: uploadRes.secure_url,
    publicId: uploadRes.public_id,
  };
}

// ===== IMAGE FETCHER (Node 18+ GLOBAL FETCH) =====
async function fetchImageBuffer(url: string): Promise<Buffer> {
  const res = await fetch(url);

  if (!res.ok) {
    throw new Error(`Failed to fetch image: ${url} (status: ${res.status})`);
  }

  const arrayBuffer = await res.arrayBuffer();
  return Buffer.from(arrayBuffer);
}
